[messages for room 12 -- rm.mickey.store

%message	19	"\"I don't have that any more,\" says Mickey.
  \"Remember?  You bought it.\""
%message	20	"\"Hello,\" says Mickey.  \"Walk to the item you want.
  Press the button to take it.  Pay me for it over here.\""
%message	21	"\"You need to be closer to choose a toy,\" says Mickey."
%message	22	"\"You've already bought everything in my store,\"
 says Mickey.  \"Try Minnie's or Goofy's store.\""
%message	23	"Please pay Mickey before leaving his store."
%message	24	"Before you take another toy, pay for what you have."
%message	25	"Pay Mickey for your toy, or return it."

